// <auto-generated />
namespace Cards.Core.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddColumnsDescriptionDueDateToCard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddColumnsDescriptionDueDateToCard));
        
        string IMigrationMetadata.Id
        {
            get { return "201309221345592_AddColumnsDescriptionDueDateToCard"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
